name: MAP573
channels:
  - conda-forge
dependencies:
#  - graph-tool
#  - jupytext
#  - numpy
#  - matplotlib
  - pandoc
  - r-aricode
  - r-base=3.6.3
  - r-corrplot
  - r-devtools
  - r-dt
  - r-foreign
  - r-ggally
  - r-knitr
  - r-readods
  - r-rcpp
  - r-rcpparmadillo
  - r-reticulate
  - r-rmarkdown
  - r-tidyverse
